services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV:-development}
    command:
      - "sh"
      - "-c"
      - |
        if [ "$NODE_ENV" = "development" ]; then
          npm run dev;
        else
          npm run start;
        fi

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-development}
    network_mode: "host"
    depends_on:
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - PC_DETAILS=${PC_DETAILS}
      - PORT=${PORT}
    command:
      - "sh"
      - "-c"
      - |
        if [ "$NODE_ENV" = "development" ]; then
          npm run dev;
        else
          npm run start;
        fi
