name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  backend:
    name: Backend Lint & Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (v22)
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Lint Backend Code
        working-directory: ./backend
        run: npm run lint

      - name: Type Check Backend Code
        working-directory: ./backend
        run: npm run type-check

  frontend:
    name: Frontend Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (v22)
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint Frontend Code
        working-directory: ./frontend
        run: npm run lint

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm run test -- --watchAll=false
